//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trial.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Travel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Travel()
        {
            this.Bookings = new HashSet<Booking>();
        }

        [DataMember]
        public int Travel_ID { get; set; }
        [DataMember]
        public string pickup_place { get; set; }
        [DataMember]
        public string drop_place { get; set; }
        [DataMember]
        public Nullable<System.DateTime> Departure_Time { get; set; }
        [DataMember]
        public Nullable<System.DateTime> Arrival_Time { get; set; }
        [DataMember]
        public Nullable<int> Bus_ID { get; set; }
        [DataMember]
        public Nullable<int> no_of_days { get; set; }
        [DataMember]
        public Nullable<int> coach_bus_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Bus_Details Bus_Details { get; set; }
        public virtual Coach_bus Coach_bus { get; set; }
    }
}
